focalpoint_get:
    path: '/focalpoint/data/get'
    defaults: { _controller: FocalPointBundle:Data:get }
    requirements: { _resource: focalpoint }

focalpoint_set:
    path: '/focalpoint/data/set'
    defaults: { _controller: FocalPointBundle:Data:set }
    requirements: { _resource: focalpoint }

focalpoint_image:
    path: '/focalpoint/data/image/:file_id/:file_version'
    defaults: { _controller: FocalPointBundle:Data:image, file_version: 1 }
    requirements: { _resource: focalpoint }

focalpoint_templates:
    path: '/focalpoint/data/templates'
    defaults: { _controller: FocalPointBundle:Data:templates }
    requirements: { _resource: focalpoint }
