services:
    # assets
    focalpoint.asset.scripts:
        class: Phlexible\FocalPointComponent\Asset\ScriptCollection
        arguments: ["%focalpoint.asset.script_path%"]
        tags:
            - {name: "asset.script", priority: -500}

    focalpoint.asset.css:
        class: Phlexible\FocalPointComponent\Asset\CssCollection
        arguments: ["%focalpoint.asset.css_path%"]
        tags:
            - {name: "asset.css"}

    # acl provider
    focalpoint.acl_provider:
        class: Phlexible\FocalPointComponent\Acl\FocalPointAclProvider
        tags:
            - {name: "security.acl.provider"}
