services:
    # acl providers
    focalpoint.acl_provider:
        class: Phlexible\FocalPointBundle\Acl\FocalPointAclProvider
        tags:
            - {name: "security.acl.provider"}

    # asset providers
    focalpoint.asset_provider:
        class: Phlexible\FocalPointBundle\AssetProvider\FocalPointAssetProvider
        arguments: [@file_locator]
        tags:
            - {name: "asset.provider", priority: -500}
