focalpoint_get:
    path: '/focalpoint/data/get'
    defaults: { module: focalpoint, controller: data, action: get }
    requirements: { _resource: focalpoint }

focalpoint_set:
    path: '/focalpoint/data/set'
    defaults: { module: focalpoint, controller: data, action: set }
    requirements: { _resource: focalpoint }

focalpoint_image:
    path: '/focalpoint/data/image'
    defaults: { module: focalpoint, controller: data, action: image }
    requirements: { _resource: focalpoint }

focalpoint_templates:
    path: '/focalpoint/data/templates'
    defaults: { module: focalpoint, controller: data, action: templates }
    requirements: { _resource: focalpoint }
