focalpoint_get:
    path: '/focalpoint/data/get'
    defaults: { module: focalpoint, controller: data, action: get }
    requirements: { _resource: focalpoint }

focalpoint_set:
    path: '/focalpoint/data/set'
    defaults: { module: focalpoint, controller: data, action: set }
    requirements: { _resource: focalpoint }

focalpoint_image:
    path: '/focalpoint/data/image/:file_id/:file_version'
    defaults: { module: focalpoint, controller: data, action: image, file_version: 1 }
    requirements: { _resource: focalpoint }

focalpoint_templates:
    path: '/focalpoint/data/templates'
    defaults: { module: focalpoint, controller: data, action: templates }
    requirements: { _resource: focalpoint }
