services:
    # assets
    focalpointAssetScripts:
        class: Phlexible\FocalPointComponent\Asset\ScriptCollection
        arguments: ["%focalpoint.asset.script_path%"]
        tags:
            - ["asset.script", {priority: -500}]

    focalpointAssetCss:
        class: Phlexible\FocalPointComponent\Asset\CssCollection
        arguments: ["%focalpoint.asset.css_path%"]
        tags:
            - ["asset.css"]

    # acl resources
    focalpointResourceFocalpoint:
        class: Zend_Acl_Resource
        arguments: [focalpoint]
        tags: [[security.acl.resource]]
