tags:
    - ["asset.translation", {namespace: "Media.strings.Focalpoint", page: focalpoint}]

services:
    # assets
    focalpointAssetScripts:
        class: Phlexible\FocalPointComponent\Asset\ScriptCollection
        arguments: ["%focalpoint.asset.script_path%"]
        tags:
            - ["asset.script", {priority: -500}]

    focalpointAssetCss:
        class: Phlexible\FocalPointComponent\Asset\CssCollection
        arguments: ["%focalpoint.asset.css_path%"]
        tags:
            - ["asset.css"]
